title: Jacob's Blog
author: Jacob
email: jacobbaskins@gmailcom
description: > # this means to ignore newlines until "baseurl:"
  This is my blog I'm making

# social links
twitter_username: Deanyboy1313 # DO NOT include the @ character, or else the build will fail!
github_username:  j-baskins # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
